require('plugins.plugins-setup')

require('core.options')
require('core.colorschema')
require('core.keymaps')

require('plugins.plg-icons')
require('plugins.lualine')
require('plugins.treesitter')
require('plugins.plg-neo')
--require('plugins.plg-cmp')
require('plugins.plg-lsp')
require('plugins.bufferline')
require('plugins.gitsigns')
require('plugins.telescope')
