return {
  'williamboman/mason-lspconfig.nvim',
  opts = {
    ensure_installed = {
      'angularls',
      'awk_ls',
      'bashls',
      'clangd',
      'cssls',
      'cssmodules_ls',
      'diagnosticls',
      'docker_compose_language_service',
      'dockerls',
      'emmet_ls',
      'eslint',
      'html',
      'jsonls',
      'lua_ls',
      'marksman',
      'powershell_es',
      'sqlls',
      'tailwindcss',
      'tsserver',
      'volar',
      'yamlls',
    },
    automatic_installation = true,
  },
  event = 'BufReadPre',
  dependencies = 'williamboman/mason.nvim',
}
